services:

  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: battleuser
      POSTGRES_PASSWORD: battlepass
      POSTGRES_DB: ai_battle_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  influxdb:
    image: influxdb:2.7-alpine
    environment:
      INFLUXDB_DB: benchmarks
      INFLUXDB_ADMIN_USER: admin
      INFLUXDB_ADMIN_PASSWORD: adminpass123
      INFLUXDB_HTTP_AUTH_ENABLED: "true"
    ports:
      - "8086:8086"
    volumes:
      - influxdb_data:/var/lib/influxdb2

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data

  backend:
    build: ./backend
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - influxdb
      - redis
    environment:
      DATABASE_URL: postgresql+psycopg2://battleuser:battlepass@postgres/ai_battle_db
      SYNC_DATABASE_URL: postgresql+psycopg2://battleuser:battlepass@postgres/ai_battle_db
      ASYNC_DATABASE_URL: postgresql+asyncpg://battleuser:battlepass@postgres/ai_battle_db
      REDIS_URL: redis://redis:6379
      INFLUXDB_URL: http://influxdb:8086
      INFLUXDB_TOKEN: your-token-here
      INFLUXDB_ORG: ai-battle
      INFLUXDB_BUCKET: benchmarks
      SECRET_KEY: your-secret-key-change-this-in-production
    volumes:
      - ./backend:/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

volumes:
  postgres_data:
  influxdb_data:
  redis_data: